version: '2'
services:
  dev:
    image: node:6.7.0
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    command: npm run watch
    working_dir: /code
    depends_on:
      - db
    networks:
      - network

  db:
    image: mongo:3.2.10
    networks:
      - network

networks:
  network:
    driver: bridge